# Check if there are the updates of a selected group automatically
# at_startup: (bool) Check at startup
# at_shutdown: (bool) Check at shutdown
auto_update:
 at_startup: false
 at_shutdown: false

# The interval of fetching repository
# If this value is too small, your operation with Pundler may take a long time
# You should set 1500 ~ 2000 to this value
# minimum_fetch_interval: (int) second
minimum_fetch_interval: 1800